# ---

# name: Targets

# on: [push, pull_request]

# env:
#   RUNNER: tools/run-tests.py

# jobs:
#   MbedOS5_K64F:
#     runs-on: ubuntu-18.04  # needed due to ppa:team-gcc-arm-embedded/ppa
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with:
#           python-version: '3.8'  # needed due to 'intelhex' module
#       - run: sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa
#       - run: sudo apt update
#       - run: sudo apt install gcc-arm-embedded python3-setuptools
#       - run: make -f ./targets/mbedos5/Makefile.travis install
#       - run: make -f ./targets/mbedos5/Makefile.travis script

#   Zephyr_Qemu_x86:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with:
#           python-version: '3.x'
#       - run: sudo apt update
#       - run: sudo apt install gperf dfu-util device-tree-compiler
#       - run: make -f ./targets/zephyr/Makefile.travis install
#       - run: make -f ./targets/zephyr/Makefile.travis script

#   NuttX_STM32F4:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: sudo apt update
#       - run: sudo apt install gcc-arm-none-eabi libnewlib-arm-none-eabi gperf
#       - run: make -f ./targets/nuttx-stm32f4/Makefile.travis install-noapt
#       - run: make -f ./targets/nuttx-stm32f4/Makefile.travis script

#   RIOT_STM32F4:
#     runs-on: ubuntu-18.04  # needed due to ppa:team-gcc-arm-embedded/ppa
#     env:
#       CC: clang
#     steps:
#       - uses: actions/checkout@v2
#       - run: sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa
#       - run: sudo apt update
#       - run: sudo apt install clang gcc-arm-embedded gcc-multilib
#       - run: make -f ./targets/riot-stm32f4/Makefile.travis install-noapt
#       - run: make -f ./targets/riot-stm32f4/Makefile.travis script

#   ESP8266:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with:
#           python-version: '2.7'  # needed due to ESP8266_RTOS_SDK/tools/gen_appbin.py
#       - run: make -f ./targets/esp8266/Makefile.travis install-noapt
#       - run: make -f ./targets/esp8266/Makefile.travis script
