# ---

# name: Test262

# on: [push, pull_request]

# env:
#   RUNNER: tools/run-tests.py

# jobs:
#   ES5_1:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         build-type: [debug, release]
#     steps:
#       - uses: actions/checkout@v2
#       - run: $RUNNER --test262 --build-type=${{ matrix.build-type }}

#   ES2015:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         buildoptions: [{type: debug, dir_suffix: '-debug'},
#                        {type: release, dir_suffix: ''}
#         ]
#         dir: [language, built-ins, annexB, harness, intl402]
#     steps:
#       - uses: actions/checkout@v2
#       - run: >-
#           $RUNNER
#           --test262-es2015=update
#           --build-type=${{ matrix.buildoptions.type }}
#           --test262-test-list=${{ matrix.dir }}
#       - uses: actions/upload-artifact@v2
#         if: success() || failure()
#         with:
#           name: Test262-ES2015-${{ matrix.dir }}-results
#           path: |
#             build/tests/test262_tests_es2015${{ matrix.buildoptions.dir_suffix }}/local/bin/test262.report

#   ESNext:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         buildoptions: [{type: debug, dir_suffix: '-debug'},
#                        {type: release, dir_suffix: ''}
#         ]
#         dir: [language, built-ins, annexB, harness, intl402]
#     steps:
#       - uses: actions/checkout@v2
#       - run: >-
#           $RUNNER
#           --test262-esnext=update
#           --build-type=${{ matrix.buildoptions.type }}
#           --test262-test-list=${{ matrix.dir }}
#       - uses: actions/upload-artifact@v2
#         if: success() || failure()
#         with:
#           name: Test262-ESNext-${{ matrix.dir }}-results
#           path: |
#             build/tests/test262_tests_esnext${{ matrix.buildoptions.dir_suffix }}/local/bin/test262.report
